# Generated by Django 5.2 on 2026-02-21 15:43

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('starter', 'Entrée'), ('main', 'Plat'), ('dessert', 'Dessert'), ('appetizer', 'Apéritif'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('servings', models.PositiveSmallIntegerField(verbose_name='Nombre de personnes')),
                ('prep_time', models.PositiveSmallIntegerField(verbose_name='Temps de préparation (min)')),
                ('cook_time', models.PositiveSmallIntegerField(default=0, verbose_name='Temps de cuisson (min)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ingrédient')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantité')),
                ('unit', models.CharField(blank=True, choices=[('g', 'Grammes'), ('kg', 'Kilogrammes'), ('ml', 'Millilitres'), ('cl', 'Centilitres'), ('l', 'Litres'), ('tsp', 'Cuillère à café'), ('tbsp', 'Cuillère à soupe'), ('piece', 'Pièce(s)'), ('bunch', 'Bouquet'), ('pm', 'Pour mémoire')], max_length=10, verbose_name='Unité')),
                ('ciqual_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='nutrition.ciqualfood', verbose_name='Aliment CIQUAL')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Ordre')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='steps/', verbose_name="Photo de l'étape")),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['order'],
            },
        ),
    ]
