# Generated by Django 5.2 on 2026-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Laisser vide = eau (1g/ml). Ex: huile=0.92, miel=1.4', max_digits=5, null=True, verbose_name='Densité (g/ml)'),
        ),
    ]
