# Generated by Django 5.2 on 2026-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiqualFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code CIQUAL')),
                ('name', models.CharField(max_length=200, verbose_name='Aliment')),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Énergie (kJ/100g)')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Protéines (g/100g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Glucides (g/100g)')),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sucres (g/100g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Lipides (g/100g)')),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='AG saturés (g/100g)')),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fibres (g/100g)')),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cholestérol (mg/100g)')),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sel (g/100g)')),
            ],
            options={
                'verbose_name': 'Aliment CIQUAL',
                'verbose_name_plural': 'Aliments CIQUAL',
                'ordering': ['name'],
            },
        ),
    ]
