# Generated by Django 5.2 on 2026-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Allergène')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Allergène',
                'verbose_name_plural': 'Allergènes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ciqualfood',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='foods', to='nutrition.allergen', verbose_name='Allergènes'),
        ),
    ]
